services:
    snapclient:
        restart: unless-stopped

        mem_reservation: "10M"
        mem_limit: "750M"

        container_name: room_name
        hostname: room_name
        devices:
            - /dev/snd
        image: kertain/snapclient:032-3
        command: snapclient -h snapserver.local -s A_2
        networks:
              default:
                    mac_address: (generate some addr here, CRUCIAL if deploying multiple instances)

networks:
    default:
        driver: bridge
