version: '3.9'
services:
    snapclient:
        restart: unless-stopped
        container_name: room_name
        hostname: room_name
        mac_address: so:me:ma:c:ad:dr
        devices:
            - /dev/snd
        image: kertain/snapclient:029
        command: snapclient -h snapserver.local -s A_2
