services:
    snapclient:
        restart: unless-stopped
        mem_reservation: "2M"
        mem_limit: "500M"
        devices:
            - /dev/snd
        image: ghcr.io/kerta1n/snapclient-docker:latest

        environment:
            - TZ=America/Indiana/Indianapolis

        container_name: room_name
        hostname: room_name

        command: snapclient -h snapserver.local -s A_2
        networks:
              default:
                    mac_address: (generate some addr here, CRUCIAL if deploying multiple instances)

networks:
    default:
        driver: bridge