version: '3.9'
services:
    snapclient:
        restart: unless-stopped
        container_name: room_name
        hostname: room_name
        devices:
            - /dev/snd
        image: kertain/snapclient:029
        command: snapclient -h snapserver.local -s A_2
        networks:
              default:
                    mac_address: (generate some addr here, CRUCIAL if deploying multiple instances)

networks:
    default:
        driver: bridge
